title: "果叔AI世界"
description: "分享AI出海干货,AI圈最新消息"
url: https://mrzhangguoguo.github.io
baseurl: ""
email: "xjzzxwork@gmail.com"
theme: minima
lang: zh-CN
timezone: Asia/Shanghai
wechat_qr: "/assets/images/qrcode_for_gh_9052aff0c5b8_258.jpg"
# Optional site-wide OG image (overridable per page via `og_image`)
# og_image: "/assets/images/og-default.png"
# 可选：主页横幅图（建议 1920×640 或 2400×800，2-3x 像素更清晰）
# hero_image: "/assets/images/hero-banner.jpg"

plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Google Search Console verification (public for branch-based Pages build)
google_site_verification: "Oox66ofB-Lc8pVOfQxDVNY0gHge_5fpPqtnF9npOC5k"

# Markdown & Syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false

collections:
  episodes:
    output: true
    permalink: /episodes/:slug/

permalink: /posts/:slug/

exclude:
  - node_modules
  - Gemfile*
  - package*.json
  - claude.md
  - Drafts
  - Templates
  # Developer docs and non-public pages (exclude from build and sitemap)
  - BLOG_GUIDE.md
  - DEPLOYMENT_CHECKLIST.md
  - LOCAL_SETUP.md
  - TEST_PLAN.md
  - post-management
  - preview.html
  - preview-post.html
  - setup-docker-proxy.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
  # Do not include admin or asset files in sitemap; hint crawlers not to index
  - scope:
      path: "public"
    values:
      sitemap: false
      robots: noindex
  - scope:
      path: "assets"
    values:
      sitemap: false
      robots: noindex
