title: "果叔AI世界"
description: "分享AI出海干货,AI圈最新消息"
url: https://mrzhangguoguo.github.io
baseurl: ""
email: "xjzzxwork@gmail.com"
theme: minima
lang: zh-CN
timezone: Asia/Shanghai
wechat_qr: "/assets/images/qrcode_for_gh_9052aff0c5b8_258.jpg"
# 可选：主页横幅图（建议 1920×640 或 2400×800，2-3x 像素更清晰）
# hero_image: "/assets/images/hero-banner.jpg"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Markdown & Syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false

collections:
  episodes:
    output: true
    permalink: /episodes/:slug/

permalink: /posts/:slug/

exclude:
  - node_modules
  - Gemfile*
  - package*.json
  - claude.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
