version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: blog-jekyll
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --watch --force_polling --livereload --baseurl ''
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle